### ISSUE TITLE
Thermal Inference configurations

### ISSUE THREAD

**Issue by supercrazysam** [enesozi/object-detection#10]
Hi @enesozi !
I am trying to recreate the thermal inference just like your video
https://youtu.be/xe_KRQ7qtQE

If I just want to do the inference.
Is it correct that I just need to change to use
1) thermal.data
2) thermal.names
3) yolov3-thermal.cfg
4) yolov3-spp-thermal .weights ?

Also, may I ask which python file do you use to create the inference result?
Since I should pass a single channel image to darknet. I am not quite should how should I modify it.

Please help!  Thanks in advance

**Comment by enesozi** [comment]
Hi,
I created the final video using OpenCV.
Yes, you need to modify those files according to yours, yet, I used yolov3-thermal-custom.cfg for this experiment. You may even use darknet.py from the submodule, it really doesn't matter. If you use pretrained weights on the same dataset that I used, it should be working correctly with the given configuration file.

**Comment by supercrazysam** [comment]
Can confirm. After I changed the config from "yolov3-thermal.cfg" to "yolov3-spp-custom.cfg"
Everything is working just fine. Thanks! Have a good day.
