### ISSUE TITLE
YOLO Weights

### ISSUE THREAD

**Issue by jeremy-jos** [enesozi/object-detection#2]
Hello Enes,

Thank you for your great medium post ! Could you provide the final weights you obtained for the YOLO classifier ?

Thank you !

**Comment by enesozi** [comment]
Hi Jeremy,
Please refer to #1

**Comment by jeremy-jos** [comment]
Thank you ! Which cfg file should I use to convert the weights to Keras .h5 format ? the yolo-thermal.cfg ?

**Comment by jeremy-jos** [comment]
The config to use were the spp-custom.
