### ISSUE TITLE
Is nvidia-docker supported on Jetson?

### ISSUE THREAD

**Issue by DennisFaucher** [enesozi/object-detection#3]
I ran ./build_docker_container.sh on my Jetson Xavier and received the error:

Step 5/9 : RUN apt-get update && apt-get install -y --no-install-recommends         build-essential         cmake         git         wget         sudo         python         libcudnn7=$CUDNN_VERSION-1+cuda10.0         libcudnn7-dev=$CUDNN_VERSION-1+cuda10.0 &&     apt-mark hold libcudnn7 &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 92c8d8acab95
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends         build-essential         cmake         git         wget         sudo         python         libcudnn7=$CUDNN_VERSION-1+cuda10.0         libcudnn7-dev=$CUDNN_VERSION-1+cuda10.0 &&     apt-mark hold libcudnn7 &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1

**Comment by enesozi** [comment]
It could be due to your target runtime platform as explained [here](https://github.com/pi-hole/docker-pi-hole/issues/519)

**Comment by DennisFaucher** [comment]
@enesozi Yes. Thank you.

**Comment by victoraranda** [comment]
@DennisFaucher Dennis, was there a solution or workaround you found?

**Comment by DennisFaucher** [comment]
No. There is no CUDA for Jetson. Need to build models off-machine.
