### ISSUE TITLE
repository does not exist

### ISSUE THREAD

**Issue by DennisFaucher** [enesozi/object-detection#4]
$ sudo ./run_docker_container.sh
Unable to find image 'thermal:darknet' locally
docker: Error response from daemon: pull access denied for thermal, repository does not exist or may require 'docker login'.

Ideas? Thank you.

**Comment by enesozi** [comment]
I assume you still couldn't build the docker image. Therefore, you can't create a container from an image that doesn't exist.

**Comment by DennisFaucher** [comment]
@enesozi Yes. I have moved on. It was worth a try. Thanks for the response.
