### ISSUE TITLE
Small, medium, large

### ISSUE THREAD

**Issue by Pari-singh** [enesozi/object-detection#5]
Hi @enesozi 

You mentioned you sampled the large objects from the train set. Could you shed some light, how did you do that? I am training model on the same dataset using yolov3-spp and just training the final layers as I am short of resources to train from scratch. Getting not so good results.

**Comment by enesozi** [comment]
What do you mean by sampling the large objects? Oversampling the bicycle class? I didn't sample any objects based on their sizes.

**Comment by Pari-singh** [comment]
@enesozi , in your blog post, you mentioned you were getting high false positives since many of the small objects were not labeled in FLIR dataset and thus you removed those images. How did you remove them? Any routine to follow?

Thanks for your time!

**Comment by enesozi** [comment]
I didn't remove any images. I just didn't use small area' as a criterion in COCO evaluation. In other words, I wanted to see how better results I can get if I use only medium and large boxes from the ground truth annotations. If you would like to remove those images from your dataset, it'd require you to visualize ground truths on the images and take a look at them.

**Comment by Pari-singh** [comment]
Oh I see, so you did the training as usual and then only while evaluating your model, you gave that criteria? Sorry, i wasn't aware of such options in COCO evaluation!

Thanks a lot!

**Comment by enesozi** [comment]
Yes, exactly. You may refer to the official [ipynb](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocoEvalDemo.ipynb) to see how it works. 

Below code snippet is an example for excluding _small area_ from the evaluation.
`
cocoEval.params.areaRng = [[32 ** 2, 1e5 ** 2],[32 ** 2, 96 ** 2], [96 ** 2, 1e5 ** 2]]
cocoEval.params.areaRngLbl = ['all', 'medium', 'large']
`
