### ISSUE TITLE
Unable to run ./start_thermal.sh

### ISSUE THREAD

**Issue by joel5638** [enesozi/object-detection#8]
@enesozi Please help me run the docker

../../../darknet: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
![Screenshot from 2020-03-09 17-19-38](https://user-images.githubusercontent.com/38422983/76210490-3ffe4b80-622a-11ea-9cc7-2b0bd7715d3c.png)

**Comment by enesozi** [comment]
Hi,
You may take a look at the [script](https://github.com/enesozi/object-detection/blob/master/run_docker_container.sh) to see how to run an nvidia docker.
